superheroes/heroes/urls.py
from . import views
from django.urls import path

app_name = 'heroes'
urlpatterns = [
    path('index', views.index, name='index'),
    path('', views.home, name='home'),
    path('<int:hero_id>/', views.detail, name='detail'),
    path('new/', views.create_hero, name='create_hero'),
    path('edit/<int:hero_id>', views.edit_hero, name='edit_hero'),
    path ('delete/<int:hero_id>/', views.delete_hero, name='delete')

]

superheroes/superheroes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('heroes/', include('heroes.urls')),
    path('', include('heroes.urls'))
]

superheroes/heroes/models.py
from django.db import models


class Hero(models.Model):
    hero_name = models.CharField(max_length=50)
    secret_identity = models.CharField(max_length=50)
    primary = models.CharField(max_length=50)
    secondary = models.CharField(max_length=50, null=True)
    catchphrase = models.CharField(max_length=50, null=True)

superheroes/heroes/views.py
from django.shortcuts import render
from .models import Hero
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse


def index(request):
    all_heroes = Hero.objects.all()
    context = {
        'all_heroes': all_heroes
    }
    return render(request, 'heroes/index.html', context)


def detail(request, hero_id):
    hero = Hero.objects.get(pk=hero_id)
    context = {
        'hero': hero
    }

    return render(request, 'heroes/detail.html', context)


def create_hero(request):
    if request.method == 'POST':
        hero_name = request.POST.get('hero_name')
        secret_identity = request.POST.get('secret')
        primary = request.POST.get('primary')
        secondary = request.POST.get('secondary')
        catchphrase = request.POST.get('catchphrase')
        new_hero = Hero(hero_name=hero_name, secret_identity=secret_identity, primary=primary, secondary=secondary, catchphrase=catchphrase)
        new_hero.save()
        return HttpResponseRedirect(reverse('heroes:index'))
    else:
        return render(request, 'heroes/create.html')


def edit_hero(request, hero_id ):
    if request.method == 'POST':
        hero = Hero.objects.get(pk=hero_id)
        hero.hero_name = request.POST.get('hero_name')
        hero.secret_identity = request.POST.get('secret')
        hero.primary = request.POST.get('primary')
        hero.secondary = request.POST.get('secondary')
        hero.catchphrase = request.POST.get('catchphrase')
        hero.save()
        return detail(request, hero_id)
    else:
        hero = Hero.objects.get(pk=hero_id)
        context = {
            'hero': hero
        }

        return render(request, 'heroes/edit.html', context)


def delete_hero(request, hero_id):
    Hero.objects.get(pk=hero_id).delete()

    return HttpResponseRedirect(reverse('heroes:index'))


def home(request):

    return render(request, 'heroes/home.html')

superheroes/heroes/templates/heroes/create.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Create a Hero</title>
</head>
<body class="p-3 mb-2 bg-secondary text-white">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'heroes:index' %}"  tabindex="-1">List of Heroes</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" href="{% url 'heroes:create_hero' %}" tabindex="-1" aria-current="page">Register a new hero</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<form action="{% url 'heroes:create_hero' %}" method="post">
    {% csrf_token %}
Hero Name:<input type="text" name="hero_name" id="hero_name" class="btn btn-dark"><br>
Secret Identity:<input type="text" name="secret" id="secret" class="btn btn-dark"><br>
Primary Ability:<input type="text" name="primary" id="primary" class="btn btn-dark"><br>
Secondary Ability:<input type="text" name="second" id="second" class="btn btn-dark"><br>
Catchphrase:<input type="text" name="catchphrase" id="catchphrase" class="btn btn-dark"><br>
<input type="submit" value="Register Hero!" class="btn btn-dark">
</form>




<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

superheroes/heroes/templates/heroes/detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>More about {{hero.hero_name}}</title>
</head>
<body class="p-3 mb-2 bg-secondary text-white">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'heroes:index' %}" aria-current="page" tabindex="-1">List of Heroes</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'heroes:create_hero' %}" tabindex="-1" aria-disabled="true">Register a new hero</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<h1>{{hero.hero_name}}</h1>
<h2>
    <ul>
        <li>Secret Identity: {{hero.secret_identity}}</li>
        <li>Super Power: {{hero.primary}}</li>
        <li>Secondary Power: {{hero.secondary}}</li>
        <li>Catchphrase: {{hero.catchphrase}}</li>
    </ul>
</h2>
<br><br>
<form action="{% url 'heroes:edit_hero' hero.id%}">
<button type="submit" class="btn btn-dark">Edit Hero</button>
</form><br>
<form action="{% url 'heroes:delete' hero.id%}">
<button type="submit" class="btn btn-danger">Delete Hero</button>
</form>





<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

superheroes/heroes/templates/heroes/edit.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Editing Hero</title>
</head>
<body class="p-3 mb-2 bg-secondary text-white">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'heroes:index' %}" aria-current="page" tabindex="-1">List of Heroes</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'heroes:create_hero' %}" tabindex="-1" aria-disabled="true">Register a new hero</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<form action="{% url 'heroes:edit_hero' hero.id%}" method="post" >
    {% csrf_token %}
Hero Name:<input type="text" name="hero_name" id="hero_name" value='{{hero.hero_name}}' class="btn btn-dark"><br>
Secret Identity:<input type="text" name="secret" id="secret" value='{{hero.secret_identity}}' class="btn btn-dark"><br>
Primary Ability:<input type="text" name="primary" id="primary" value='{{hero.primary}}' class="btn btn-dark"><br>
Secondary Ability:<input type="text" name="second" id="second" value='{{hero.secondary}}' class="btn btn-dark"><br>
Catchphrase:<input type="text" name="catchphrase" id="catchphrase" value='{{hero.catchphrase}}' class="btn btn-dark"><br>
<input type="submit" value="Edit Hero!" class="btn btn-dark">
</form>
<form action="{% url 'heroes:delete' hero.id%}">
<button type="submit" class="btn btn-danger">Delete Hero</button>
</form>




<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

superheroes/heroes/templates/heroes/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Heroes</title>
</head>
<body class="p-3 mb-2 bg-secondary text-white">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'heroes:index' %}" aria-current="page" tabindex="-1">List of Heroes</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'heroes:create_hero' %}" tabindex="-1" aria-disabled="true">Register a new hero</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<h1 align="center">Welcome to the Hero Registration Site</h1>
<table align="center" width="80%">
    <tr>
        <td><h3>We support Tony Stark in his efforts to increase regulation on heroes /w<br> increase oversite so the purpose of this page is to keep track of known heroes</h3></td>
        <td>{% load static %}<img src="{% static 'heroes/cap.jpg' %}" width="80%"></td>
    </tr>
</table>



<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

superheroes/heroes/templates/heroes/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Heroes</title>
</head>
<body class="p-3 mb-2 bg-secondary text-white">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'heroes:index' %}" aria-current="page" tabindex="-1">List of Heroes</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'heroes:create_hero' %}" tabindex="-1" aria-disabled="true">Register a new hero</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<h1>Registered Heroes:</h1>
<ul>
    {% for hero in all_heroes %}
    <li><h2><a href="{% url 'heroes:detail' hero.id %}" class="btn btn-dark">{{hero.hero_name}}</a></h2></li>
    {% endfor %}
</ul>


<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>